### ISSUE TITLE
webpack-plugin-serve/client is wrongly transpiled with babel

### ISSUE THREAD

**Issue by TrySound** [shellscape/webpack-plugin-serve#57] opened 2018-12-14 21:45 UTC
- Webpack Version: 4.27.1
- Operating System (or Browser): mac os sierra
- Node Version: 8.12
- webpack-plugin-serve Version: 0.2.2

### How Do We Reproduce?

- start the project https://github.com/TrySound/wp-bug
- remove webpack-plugin-serve from babel-loader exclude

### Expected Behavior

webpack-plugin-serve/client should not be touched by babel loader if node_modules are excluded

### Actual Behavior

webpack-plugin-serve/client is tranpiled by babel loader even with `exclude: /node_modules/`

**Comment by shellscape** [comment] 2018-12-14 22:09
Is this a plugin problem or a webpack problem though? I'm not sure if there's anything we can do about that from our side of things. As a test, please try adding `webpack-plugin-serve/client` to the exclude option.

**Comment by TrySound** [comment] 2018-12-14 22:16
Yeah, this worked. But it's really weird and unexpected thing. Would be good to see it in documentation.

**Comment by shellscape** [comment] 2018-12-14 22:42
Before we document it we need to be certain what the cause is. @PlayMa256 suspects that the `exclude` option doesn't exclude that script because it's defined as an `entry`.

**Comment by TrySound** [comment] 2018-12-14 22:45
Yeah, I think the same. Did you work around it in webpack-dev-serve/webpack-serve somehow? Or the code was already in es5?

**Comment by shellscape** [comment] 2018-12-14 22:47
yeah webpack-serve was already ES5 (or we transpiled it before publish, I can't recall, but one of those is true). webpack-dev-server is ES3.

**Comment by TrySound** [comment] 2018-12-14 22:51
Uh

**Comment by shellscape** [comment] 2018-12-16 14:41
@TrySound have you determined if this is a bug with this plugin or if it is a bigger webpack issue?

**Comment by PlayMa256** [comment] 2018-12-16 19:39
I'll see if i can ping sokra on twitter, IF he answers... otherwise i guess we can close this, since it is something we are not sure about. If we have a precisely answer about this, we can document properly.

**Comment by PlayMa256** [comment] 2018-12-17 11:39
Well, turned out that sokra had to bring my attention to this. Apparently it is indeed not being transpiled even if it is not on the exclude options.

As you can see @TrySound https://gist.github.com/PlayMa256/832f008a3a3cb056b537ca715cb15d60 it is not being touched by babel apparently either. 
Even adding ie11 to browserlist (https://github.com/PlayMa256/wp-bug/) it was not touched at all!

I don't really have any idea, why it was touched by babel-loader on your env and not on mine.

**Comment by TrySound** [comment] 2018-12-17 12:44
Did you tried to add serve to plugins list?

**Comment by PlayMa256** [comment] 2018-12-17 13:06
Yep, added and still. Class constructor is not supported on ie11 and even adding that to browserlist didn't make it be transpiled. Can you post your eval of clientSocket?

**Comment by TrySound** [comment] 2018-12-17 14:12
Were you able to reproduce it here?
https://github.com/TrySound/wp-bug

**Comment by PlayMa256** [comment] 2018-12-17 14:16
Nop. The same code i pasted on the gist is the same i'm seeing while compiling from your repository, although mine was just a fork. This is really interesting

**Comment by TrySound** [comment] 2018-12-24 15:07
Seems like this is not a problem anymore. I setup nano and serve from the beginning and they work great.

**Comment by PlayMa256** [comment] 2018-12-24 15:17
Good to know!

**Closed by PlayMa256** 2018-12-24 15:17 UTC
Labels: c¹ ⋅ discussion, c⁴ ⋅ need more info
