### ISSUE TITLE
ramdisk throws "no such file or directory, symlink ..." if webpack `output.path` is specified

### ISSUE THREAD

**Issue by agilgur5** [shellscape/webpack-plugin-serve#152] opened 2019-08-21 03:42 UTC
Not sure if this is an upstream issue in `webpack-plugin-ramdisk` or an issue here.

- Webpack Version: 4.9.1
- Operating System (or Browser): macOS High Sierra 10.13.6
- Node Version: 10.16.0
- webpack-plugin-serve Version: 0.12.0

### How Do We Reproduce?

Literally just setting `ramdisk: true`

### Expected Behavior

Builds and serves content same as when `ramdisk` isn't set, but faster (and not output to disk).

### Actual Behavior

```bash
⬡ wps: Ramdisk enabled
⬡ webpack-plugin-ramdisk: Build being written to /Volumes/wps/49d4ada5043fbb2f01d098d183664fc2/build
...

Error: ENOENT: no such file or directory, symlink '/Volumes/wps/49d4ada5043fbb2f01d098d183664fc2/build' -> '/path-to-my-project-dir/build/'
    at symlinkSync (fs.js:909:3)
    at WebpackPluginServe.init (/path-to-my-project-dir/node_modules/webpack-plugin-serve/lib/plugins/ramdisk.js:83:5)
    ...
```

It does delete the `build` directory before it errors out.
`ls /Volumes/wps/` shows nothing, `ls -a` shows a `.fseventsd` directory.

**Comment by shellscape** [comment] 2019-08-21 14:44
Thanks for the issue :beer:

_(Your webpack versions is super out of data. Would highly recommend updating if you're able, there have been a lot of performance improvements)_

Well this one is damn peculiar. Would you have the time to clone `webpack-plugin-ramdisk`, `npm install && npm run test`? That might reveal the root cause here. If the tests all pass on the ramdisk plugin then we'll know the problem exists with WPS here.

**Comment by agilgur5** [comment] 2019-08-21 22:28
Thanks for the quick response @shellscape!

(_Oh, I didn't even realize that, I've been waiting for v5 but didn't update minors ha. Been going through and doing major upgrades of all my devDeps (including `webpack-serve` -> `webpack-plugin-serve`), but didn't think to update webpack minors_)

Sure, did that, tests all seem to pass, here's the output:
```
⠦ ⬡ webpack-plugin-ramdisk: Initializing RAMdisk. You may be prompted for credentials
⠋ ⬡ webpack-plugin-ramdisk: Initializing RAMdisk. You may be prompted for credentials
⠧ multi › multi config
⠏ multi › multi config

  5 tests passed
```

Let me know if there's something else I should try.

**Comment by agilgur5** [comment] 2019-08-21 23:48
I updated `webpack` to latest in particular because `webpack-plugin-serve` has a peerDep of `webpack@^4.20.2` (and `webpack-plugin-ramdisk` of `webpack@^4.20.0`), but I'm still getting the same error, so it's not related to the older `webpack@4` version.

**Comment by shellscape** [comment] 2019-08-21 23:56
That's interesting. Thanks for going the extra mile there. I'll need to take a good look at the code to see if anything stands out that could be causing this problem. I might ask you to try a diagnostic branch or make some code edits on your end to get to the bottom of this. Stay tuned...

**Comment by shellscape** [comment] 2019-09-16 18:48
@agilgur5 my apologies that it's taken me so long to get back to you on this. Life has a habit of throwing curveballs.

I've created a logging branch for you. To use it you'll have to do the following:

1. Update your `webpack-plugin-serve` dependency to point at the branch: `"webpack-plugin-serve": "shellscape/webpack-plugin-serve#log/ramdisk",`
1. Add the following to your WPS options: `log: { level: 'debug' },`

When you run your app, you should see log output similar to this:

```console
⬡ wps: ramdisk → hasPlugin: false
⬡ wps: ramdisk → output path: /code/webpack/webpack-plugin-serve/test/fixtures/simple/output
⬡ wps: ramdisk → lastSegment: output
⬡ wps: ramdisk → newPath: a8b75d9b8487e31bfb91f9ee6e3ec66d/output
⬡ wps: ramdisk → compiler.options.output.path: a8b75d9b8487e31bfb91f9ee6e3ec66d/output
⬡ wps: Ramdisk enabled
⬡ webpack-plugin-ramdisk: Initializing RAMdisk. You may be prompted for credentials
⬡ webpack-plugin-ramdisk: Build being written to /Volumes/wps/a8b75d9b8487e31bfb91f9ee6e3ec66d/output
⬡ wps: ramdisk → symlink: /Volumes/wps/a8b75d9b8487e31bfb91f9ee6e3ec66d/output to /code/webpack/webpack-plugin-serve/test/fixtures/simple/output
```

Hopefully that will shed some light onto what's ailing your setup there.

**Comment by agilgur5** [comment] 2019-10-30 22:02
Ok, I switched to the logging branch and added the debug level logging config. Got the same error, log below:

```
⬡ wps: ramdisk → hasPlugin: false
⬡ wps: ramdisk → output path: /path-to-my-project-dir/build/
⬡ wps: ramdisk → lastSegment: build
⬡ wps: ramdisk → newPath: 49d4ada5043fbb2f01d098d183664fc2/build
⬡ wps: ramdisk → compiler.options.output.path: 49d4ada5043fbb2f01d098d183664fc2/build
⬡ wps: Ramdisk enabled
⬡ webpack-plugin-ramdisk: Initializing RAMdisk. You may be prompted for credentials
⬡ webpack-plugin-ramdisk: Build being written to /Volumes/wps/49d4ada5043fbb2f01d098d183664fc2/build
⬡ wps: ramdisk → symlink: /Volumes/wps/49d4ada5043fbb2f01d098d183664fc2/build to /path-to-my-project-dir/build/
/path-to-my-project-dir/node_modules/webpack-cli/bin/cli.js:281
                                throw err;
                                ^

Error: ENOENT: no such file or directory, symlink '/Volumes/wps/49d4ada5043fbb2f01d098d183664fc2/build' -> '/path-to-my-project-dir/build/'
    at symlinkSync (fs.js:909:3)
    at WebpackPluginServe.init (/path-to-my-project-dir/node_modules/webpack-plugin-serve/lib/plugins/ramdisk.js:94:5)
    at WebpackPluginServe.hook (/path-to-my-project-dir/node_modules/webpack-plugin-serve/lib/index.js:177:25)
    at WebpackPluginServe.apply (/path-to-my-project-dir/node_modules/webpack-plugin-serve/lib/index.js:128:10)
    at webpack (/path-to-my-project-dir/node_modules/webpack/lib/webpack.js:51:13)
   ....
```

> my apologies that it's taken me so long to get back to you on this. Life has a habit of throwing curveballs.

Sure, sure, didn't expect an immediate response, I maintain some libraries too. Was more concerned that the comments I raised in https://github.com/shellscape/webpack-plugin-serve/issues/151#issuecomment-526403200 and the commit didn't get a response 😅

**Comment by shellscape** [comment] 2019-10-30 22:41
Hrm, with that log output I really have no idea why that's not working on your side. The logs show that everything is aligned.

**Comment by agilgur5** [comment] 2019-11-01 16:16
> Hrm, with that log output I really have no idea why that's not working on your side. The logs show that everything is aligned.

Yea, I even tried clearing cache and fresh installing all `node_modules` but it still errors out the same way.

Any chance you can try the [repro branch](https://github.com/agilgur5/front-end-base/tree/ramdisk-issues) I linked above? `npm install` -> `npm run build:hmr`. maybe some issue with transitive deps or something?

**Comment by shellscape** [comment] 2019-11-01 16:17
For sure, I totally missed that. I'll do that today.

**Comment by shellscape** [comment] 2019-11-01 17:04
OK I went through your branch there. What I found was:

- wps+ramdisk is actually creating the RAMDisk at /Volumes/wps successfully
- It's not cleaning up after the first run because webpack exists with nonzero. So `sudo umount /Volumes/wps` should get rid of the volume
- It looks like webpack (not the cli, I tried nano to confirm) is having some kind of trouble creating the output directory, and I have no idea why.

I think you might have some kind of config that just doesn't mesh well with this. Unfortunately I don't have the time right now that I'd need in order to slowly reduce the branch's config to something more simple in order to identify the problem. You'll either have to start tearing away bits (I'd start with plugins) bit by bit to see what the issue is, or go in reverse and start with a basic, bare bones build (e.g. one js file) and slowly start adding complexity, to try and figure out what is causing the problem. From there we can source dive the offender and try to figure a workaround.

Edge cases are no fun.

**Comment by agilgur5** [comment] 2019-11-03 04:18
> OK I went through your branch there. What I found was:

Thanks for taking a look -- guess it's not something machine-specific at least!
 
> * wps+ramdisk is actually creating the RAMDisk at /Volumes/wps successfully

Yep, I actually mentioned that in my initial issue comment

> * It's not cleaning up after the first run because webpack exists with nonzero. So `sudo umount /Volumes/wps` should get rid of the volume

Gotcha, wasn't sure if that was meant to be left there or not. It showed up on my desktop on macOS so I just hit "Eject" on it.

> * It looks like webpack (not the cli, I tried nano to confirm) is having some kind of trouble creating the output directory, and I have no idea why.
> 
> I think you might have some kind of config that just doesn't mesh well with this. Unfortunately I don't have the time right now that I'd need in order to slowly reduce the branch's config to something more simple in order to identify the problem. You'll either have to start tearing away bits (I'd start with plugins) bit by bit to see what the issue is, or go in reverse and start with a basic, bare bones build (e.g. one js file) and slowly start adding complexity, to try and figure out what is causing the problem. From there we can source dive the offender and try to figure a workaround.
> 
> Edge cases are no fun.

Well, I tried the "tearing away bits" part and kept commenting out stuff and trying to build until I basically commented out the entire file (0 loaders or `module:` at all, 0 plugins other than `wps`, 0 middleware config for `wps`, no `optimization:`, no `resolve:`, a simplified `filename:` with no hashes and then no `filename:`, and a simplified entrypoint with no `./` and that ensured `webpack-plugin-serve/client` was last) annnnd then I still got the error... 

I guess I'll have to try the reverse route but I'm pretty stumped as to why that super minimal config gets the error if it's really the config's fault. Really sounding like it might be some random transitive dependency instead 😕

**Comment by shellscape** [comment] 2019-11-03 14:49
> I'm pretty stumped as to why that super minimal config gets the error if it's really the config's fault

_When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth_

Being silly of course, but we've got a whole set of test suites, I'm using it daily on Mac (as are several others in the company I work for) and ~6k other users, of which I'm wager a good number of are on macs. Now that's not being said to discount the fact that the branch you put together absolutely fails - that's without question. Something isn't right. But we've got enough folks using it where it _is_ working, on simple and complex configs alike, that the only explanation that makes any logical sense is that it's the result of that particular config. It's also worth saying that it's not _your_ fault or how you wrote the config. It's more than likely a conflict in webpack core, brought on by a very specific condition that your config just happens to trigger. I saw that a million times while a part of the webpack core org, and it's one of the more frustrating parts of webpack (and a large reason for why I moved my efforts over to Rollup)

**Comment by agilgur5** [comment] 2019-12-04 01:39
> _When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth_

Well what remains is a very simple config that has little other than `webpack-plugin-serve`, so it doesn't really pinpoint any specific piece of the config being broken.

Here's a near absolute minimum branch that still reproduces the error: https://github.com/agilgur5/front-end-base/tree/ramdisk-issues-minimal . I pared down more-and-more in progressive commits until there was basically nothing, but still ran into it 😕 

It also doesn't seem to be some issue with transitive dependencies, as uninstalled virtually all `dependencies` and `devDependencies`, leaving only `webpack`, `webpack-cli`, and `webpack-plugin-serve`, and the error still occurs.

I'm shooting blanks here 😖 

> I'm using it daily on Mac (as are several others in the company I work for) and ~6k other users, of which I'm wager a good number of are on macs

Do you know how many are using the `ramdisk` feature specifically though? Since that's like

**Comment by agilgur5** [comment] 2019-12-04 01:48
Ok, I seem to have found the issue after a tiny bit more digging: if `output.path` is specified, the error occurs.
Otherwise, when `output.path` is _not_ specified, it works without errors in any of my previous reproductions; even my full config works. It literally has nothing to do with all my configuration, it's just `output.path` 😂😭😭😭 

The problem there of course is that if `output.path` isn't set, webpack defaults to `./dist/`, and then it can't be configured elsewhere if a user wants the output to be in a different directory.

Haven't investigated further to understand _why_ `output.path` is the culprit or if there's a fix or workaround available.

**Comment by agilgur5** [comment] 2019-12-17 22:37
@shellscape any chance you'd be able to look into this now that I've found the root cause?

**Comment by agilgur5** [comment] 2020-02-05 04:18
@shellscape never heard from you...

**Comment by shellscape** [comment] 2020-02-05 12:42
Thanks for the ping. It's been a crazy few months on my end. I ended up getting laid off the day after your reply with the root cause, so I went into full job search mode and had to step away from open source for a small bit there. I'm almost back to normal with work and family life so I'll get back to this when I have the chance, rest assured.

**Comment by agilgur5** [comment] 2020-02-27 07:02
Sorry to hear that 😞 Unfortunately have some first-hand experience with that as well, so I can certainly understand OSS goes pretttty far in the backseat during that.

Now that we've got the "busy" status on GitHub I do try to update that so I get pushed less and people are more aware (I pay attention to them at least, idk about the average user though).

Conversely, I noticed you had responded to other issues so I thought you just forgot about this.

Hope you get settled in soon and things are steadier!

**Comment by shellscape** [comment] 2020-02-27 12:24
Yeah this isn't low hanging fruit and will take a lot more investment of time. Replying to issues is pretty cheap in that regard. We'll get to it, just going to be a while.

**Comment by peterkelly** [comment] 2020-05-23 13:54
Looks like it's caused by 3ca6e830eac93525bbed9142fa76e991caee967b. I have a config that uses `output.path` and when I comment out the changes in that commit it works.

**Comment by shellscape** [comment] 2020-05-25 04:28
@peterkelly unless you can point to the line causing the error, it's irresponsible to suggest that an entire commit should be commented out as a fix. Nothing in that commit has side effects on the variables that the ramdisk portion of the code uses.

**Comment by peterkelly** [comment] 2020-06-18 18:47
The issue occurs because the code in that commit assumes `compiler.options.output` is a string (since it passes it to `path.join`). However, it some configurations, `compiler.options.output` can be an object, e.g.:

```
    output: {
        globalObject: "self",
        filename: "[name].js",
        path: path.join(__dirname, "www")
    },
```

It seems that the most promising approach would be to check if `compiler.options.output` is an object, and if so, use it's `path` property instead. I can put together a pull request which does this if you like, with the caveat that I'm not familiar enough with the feature this code is supporting to be sure I'm testing it properly.

BTW, I wasn't trying to suggest in my previous comment that the entire commit should be reverted (it was obviously made for a good reason) - I was just trying to assist by pinpoint the change that introduced the bug.

**Comment by shellscape** [comment] 2020-06-18 20:13
Thanks for spending time on this. I'd be totally open to a PR

**Comment by agilgur5** [comment] 2020-06-18 22:46
> BTW, I wasn't trying to suggest in my previous comment that the entire commit should be reverted (it was obviously made for a good reason) - I was just trying to assist by pinpoint the change that introduced the bug.

Yea I think this got miscommunicated on both ends. As someone that looks at `blame` often to discern root cause I'll do the same thing, referencing a PR and narrowing to line when possible. Being a maintainer too I also hide comments that may be overbroad because some readers can be quick to copy+paste, etc something without knowing the ramifications of that that a maintainer is more aware of.

Glad to see everyone's on the same page now and that root cause may have been found!

**Comment by peterkelly** [comment] 2020-06-19 09:49
I've just realised that the problem was slightly different to what I initially thought, and that commit 14d2af48b93bec08d63a95d2f9c4d4ab1f01ca63 fixes the problem I've been having. Specifically, I don't have `publicPath` set in my config, and that commit fixes this case. So with version 1.0.1 (which includes this fix) everything is fine on my end.

I believe my problem was different to the issue @agilgur5 reported.

**Comment by shellscape** [comment] 2020-11-28 01:32
So I spent a few hours on the original problem in this issue and came up empty. Given the age of the issue and that the maintainers have been unable to reproduce reliably locally, we're going to have to close this one. That said, we're totally open to a PR in either this plugin or the webpack-plugin-ramdisk plugin.

**Closed by shellscape** 2020-11-28 01:32 UTC
Labels: s¹ 🔥🔥🔥 critical, t¹ 🐞 bug
